# Day 7 – Dataset Summary Report

## Pandas Dataset Exploration

This notebook uses Python and Pandas to load and explore the provided student CSV dataset. It demonstrates the basic structure and characteristics of the dataset, including rows, columns, index, data types, descriptive statistics, and missing values.

## 1. Import Pandas

In [1]:
import pandas as pd

## 2. Load the CSV Dataset

The dataset is loaded into a Pandas DataFrame using `read_csv()`.

In [2]:
df = pd.read_csv("Day7_Student_Dataset.csv")

print("Dataset loaded successfully.")

Dataset loaded successfully.

## 3. Inspect the First Few Rows – `head()`

`head()` displays the first five rows of the DataFrame by default.

In [3]:
df.head()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow

## 4. Inspect the Last Few Rows – `tail()`

`tail()` displays the last five rows of the DataFrame by default.

In [4]:
df.tail()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

## 5. View Random Samples – `sample()`

`sample()` returns randomly selected rows from the dataset.

In [5]:
df.sample(5, random_state=42)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
11,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi

## 6. Check Dataset Shape

`shape` returns the number of rows and columns in the form `(rows, columns)`.

In [6]:
print("Shape:", df.shape)
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Shape: (25, 7)
Number of rows: 25
Number of columns: 7

## 7. View Column Names – `columns`

`columns` displays the names of all features/columns in the DataFrame.

In [7]:
print("Columns:")
print(df.columns.tolist())

Columns:
['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage', 'City']

## 8. View the DataFrame Index – `index`

`index` shows the row labels/index of the DataFrame.

In [8]:
print("Index:")
print(df.index)

Index:
RangeIndex(start=0, stop=25, step=1)

## 9. Check Data Types – `dtypes`

`dtypes` shows the data type of each column.

In [9]:
print(df.dtypes)

Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

## 10. Dataset Information – `info()`

`info()` provides a concise summary including the number of entries, column names, non-null counts, and data types.

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

## 11. Descriptive Statistics – `describe()`

`describe()` provides basic statistical information for numeric columns, including count, mean, standard deviation, minimum, quartiles, and maximum.

In [11]:
df.describe()

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

## 12. Missing Value Analysis

`isna()` identifies missing values. `sum()` counts the missing values in each column.

In [12]:
missing_values = df.isna().sum()

print("Missing values in each column:")
print(missing_values)

Missing values in each column:
Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

## 13. Check Whether the Dataset Contains Any Missing Values

In [13]:
total_missing = df.isna().sum().sum()

print("Total missing values:", total_missing)

if total_missing == 0:
    print("No missing values were found in the dataset.")
else:
    print("The dataset contains missing values.")

Total missing values: 3
The dataset contains missing values.

## 14. Data Types Summary

In [14]:
print("Numeric columns:")
print(df.select_dtypes(include="number").columns.tolist())

print("\nNon-numeric columns:")
print(df.select_dtypes(exclude="number").columns.tolist())

Numeric columns:
['Student_ID', 'Age', 'Marks', 'Attendance_Percentage']

Non-numeric columns:
['Name', 'Course', 'City']

## 15. Dataset Summary Observations

The following observations are based directly on the loaded dataset.

In [15]:
observations = [
    'The dataset contains 25 rows and 7 columns.',
    'The available features are: Student_ID, Name, Age, Course, Marks, Attendance_Percentage, City.',
    'There are 4 numeric column(s): Student_ID, Age, Marks, Attendance_Percentage.',
    'There are 3 non-numeric column(s): Name, Course, City.',
    "The 'Marks' column contains 1 missing value(s).",
    "The 'Attendance_Percentage' column contains 1 missing value(s).",
    "The 'City' column contains 1 missing value(s)."
]

for number, observation in enumerate(observations, start=1):
    print(f"{number}. {observation}")

1. The dataset contains 25 rows and 7 columns.
2. The available features are: Student_ID, Name, Age, Course, Marks, Attendance_Percentage, City.
3. There are 4 numeric column(s): Student_ID, Age, Marks, Attendance_Percentage.
4. There are 3 non-numeric column(s): Name, Course, City.
5. The 'Marks' column contains 1 missing value(s).
6. The 'Attendance_Percentage' column contains 1 missing value(s).
7. The 'City' column contains 1 missing value(s).

## 16. Overall Dataset View

A final complete view of the DataFrame is displayed below.

In [16]:
df

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar
10,1011,Vivaan Kapoor,20,AI,91.0,94.0,Jaipur
11,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi
12,1013,Rahul Das,23,Data Science,72.0,81.0,Kolkata
13,1014,Sana Malik,18,AI,89.0,92.0,NaN
14,1015,Karan Joshi,20,Computer Science,77.0,85.0,Chandigarh
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

## Conclusion

The dataset has been successfully loaded and explored using Pandas. The notebook demonstrates `read_csv()`, `head()`, `tail()`, `sample()`, `shape`, `columns`, `index`, `dtypes`, `info()`, `describe()`, and missing-value analysis.

The observations above are based on the actual CSV dataset provided for the Day 7 assignment.